#!/usr/bin/env bash
# setup-nginx.sh — Prepares the Nginx stream config for the TCP relay.
# This script DOES NOT restart or reload Nginx. Review the generated config
# and run: nginx -t && systemctl reload nginx

set -euo pipefail

DOMAIN="${1:-}"
CERT_DIR="${2:-/etc/letsencrypt/live/${DOMAIN}}"
NGINX_CONF="/etc/nginx/nginx.conf"
STREAM_CONF="/etc/nginx/conf.d/relay-stream.conf"

if [[ -z "$DOMAIN" ]]; then
    echo "Usage: $0 <domain> [cert-dir]"
    echo "  domain   — hostname used in TLS cert, e.g. relay.example.com"
    echo "  cert-dir — path to dir containing fullchain.pem and privkey.pem"
    echo "             (default: /etc/letsencrypt/live/<domain>)"
    exit 1
fi

# Check that Nginx has the stream module
if ! nginx -V 2>&1 | grep -q -- '--with-stream'; then
    echo "ERROR: Nginx does not have the stream module (--with-stream)."
    echo "Install nginx-full or recompile with stream support."
    exit 1
fi

# Check that nginx.conf doesn't already have a stream block
if grep -q '^\s*stream\s*{' "$NGINX_CONF"; then
    echo "WARNING: $NGINX_CONF already contains a 'stream' block."
    echo "Adding a separate include instead."
    WRITE_INCLUDE=1
else
    WRITE_INCLUDE=0
fi

cat > "$STREAM_CONF" <<EOF
# TCP relay — TLS termination on port 443, forwarded to Go relay on 9000.
# Generated by setup-nginx.sh — review before reloading Nginx.

stream {

    upstream relay_backend {
        server 127.0.0.1:9000;
    }

    server {
        listen 443 ssl;

        ssl_certificate     ${CERT_DIR}/fullchain.pem;
        ssl_certificate_key ${CERT_DIR}/privkey.pem;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        proxy_pass          relay_backend;
        proxy_timeout       3600s;
        proxy_connect_timeout 10s;
    }

}
EOF

echo "Written: $STREAM_CONF"

if [[ "$WRITE_INCLUDE" -eq 1 ]]; then
    # Nginx already has a stream block in nginx.conf — we can't add another.
    # The generated file must be merged manually or included inside the existing block.
    echo ""
    echo "ACTION REQUIRED:"
    echo "  $NGINX_CONF already has a stream{} block."
    echo "  Copy the 'upstream' and 'server' sections from $STREAM_CONF"
    echo "  into the existing stream{} block in $NGINX_CONF, then remove $STREAM_CONF."
else
    # Append an include directive to nginx.conf so the stream block is picked up.
    # The include goes at the top level (outside http{}), just before the last closing brace.
    if grep -q "include $STREAM_CONF" "$NGINX_CONF"; then
        echo "$NGINX_CONF already includes $STREAM_CONF — no change."
    else
        # Insert include line before the last line of nginx.conf
        sed -i "\$i\\include ${STREAM_CONF};" "$NGINX_CONF"
        echo "Added 'include ${STREAM_CONF};' to $NGINX_CONF"
    fi
fi

echo ""
echo "Next steps:"
echo "  1. Review $STREAM_CONF"
echo "  2. Verify cert paths: ${CERT_DIR}/fullchain.pem and privkey.pem exist"
echo "  3. nginx -t"
echo "  4. systemctl reload nginx"
