#!/usr/bin/env bash
# setup-nginx.sh — Writes the Nginx HTTP site config for the TCP relay.
#
# The relay now uses HTTP/1.1 Upgrade (WebSocket-style handshake) so that
# DPI appliances see a legitimate HTTPS/WebSocket session.  After the 101
# the connection is a raw byte pipe — no WebSocket framing, no XOR overhead.
#
# This script DOES NOT reload Nginx.  Review the generated config, then run:
#   nginx -t && systemctl reload nginx
#
# Usage:
#   ./setup-nginx.sh <domain> [cert-dir] [relay-port] [listen-port]
#
# Arguments:
#   domain       hostname in the TLS cert, e.g. relay.example.com (required)
#   cert-dir     directory containing fullchain.pem and privkey.pem
#                (default: /etc/letsencrypt/live/<domain>)
#   relay-port   port the Go relay listens on locally (default: 9000)
#   listen-port  HTTPS port Nginx listens on (default: 443)

set -euo pipefail

DOMAIN="${1:-}"
CERT_DIR="${2:-/etc/letsencrypt/live/${DOMAIN}}"
RELAY_PORT="${3:-9000}"
LISTEN_PORT="${4:-443}"

SITE_CONF="/etc/nginx/sites-available/relay-${DOMAIN}.conf"
SITE_LINK="/etc/nginx/sites-enabled/relay-${DOMAIN}.conf"

# ── validation ────────────────────────────────────────────────────────────────

if [[ -z "$DOMAIN" ]]; then
    echo "Usage: $0 <domain> [cert-dir] [relay-port] [listen-port]"
    echo ""
    echo "  domain       e.g. relay.example.com"
    echo "  cert-dir     default: /etc/letsencrypt/live/<domain>"
    echo "  relay-port   default: 9000"
    echo "  listen-port  default: 443"
    exit 1
fi

if [[ ! -d "$CERT_DIR" ]]; then
    echo "WARNING: cert dir does not exist yet: $CERT_DIR"
    echo "  (create it before reloading Nginx, or adjust the path in $SITE_CONF)"
fi

# Warn if Nginx has the old stream-module config for this relay.
OLD_STREAM="/etc/nginx/conf.d/relay-stream.conf"
if [[ -f "$OLD_STREAM" ]]; then
    echo "WARNING: found old stream-module config: $OLD_STREAM"
    echo "  It must be removed before the HTTP config works on port ${LISTEN_PORT}."
    echo "  Run:  sudo rm $OLD_STREAM  then  nginx -t  to verify."
    echo ""
fi

# ── write site config ─────────────────────────────────────────────────────────

mkdir -p "$(dirname "$SITE_CONF")"

cat > "$SITE_CONF" <<EOF
# Nginx site config for the TCP relay.
# Generated by setup-nginx.sh — edit with care.
#
# Design: client sends a WebSocket-style HTTP/1.1 Upgrade request.
# Nginx terminates TLS and proxies the upgrade to the Go relay on
# 127.0.0.1:${RELAY_PORT}.  After the 101, the connection is a raw byte pipe.
# No WebSocket framing or XOR masking is ever performed — zero CPU overhead.

server {
    listen ${LISTEN_PORT} ssl;
    server_name ${DOMAIN};

    # ── TLS ──────────────────────────────────────────────────────────────────
    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    # ── WebSocket / raw-upgrade proxy ─────────────────────────────────────────
    location /relay {
        proxy_pass              http://127.0.0.1:${RELAY_PORT};

        # Required for HTTP/1.1 Upgrade (WebSocket handshake).
        proxy_http_version      1.1;
        proxy_set_header        Upgrade    \$http_upgrade;
        proxy_set_header        Connection "upgrade";
        proxy_set_header        Host       \$host;

        # Large file transfers; disable buffering and timeouts.
        proxy_request_buffering off;
        proxy_buffering         off;
        client_max_body_size    0;

        # Keep the tunnel alive for long-running transfers (1 hour).
        proxy_read_timeout      3600s;
        proxy_send_timeout      3600s;
    }

    # Reject everything else.
    location / {
        return 404;
    }
}
EOF

echo "Written: $SITE_CONF"

# ── enable site ───────────────────────────────────────────────────────────────

if [[ -d /etc/nginx/sites-enabled ]]; then
    if [[ ! -L "$SITE_LINK" ]]; then
        ln -s "$SITE_CONF" "$SITE_LINK"
        echo "Enabled: $SITE_LINK"
    else
        echo "Already enabled: $SITE_LINK"
    fi
else
    echo "No sites-enabled dir found — include manually in nginx.conf:"
    echo "  include ${SITE_CONF};"
fi

# ── summary ───────────────────────────────────────────────────────────────────

echo ""
echo "Next steps:"
echo "  1. Review $SITE_CONF"
if [[ ! -f "${CERT_DIR}/fullchain.pem" ]]; then
    echo "  2. Obtain TLS cert:  certbot certonly --nginx -d ${DOMAIN}"
else
    echo "  2. Cert found at ${CERT_DIR} — OK"
fi
if [[ -f "$OLD_STREAM" ]]; then
    echo "  3. Remove old config:  sudo rm $OLD_STREAM"
fi
echo "  4. Test:    nginx -t"
echo "  5. Reload:  systemctl reload nginx"
